module.exports = function(six){
var onetable=/\|\|\s?([^\n]*)\s/g;
var onetable2=/\|\|\s/g;
var twotable=/\|\|\s?([^\n]*)\s\|\|/g;
var param = six.replace(twotable,"$1");
var loop = 1;
var paramarray = param.split("||");

var paramlen = paramarray.length;
var realparam = paramarray;
paramarray = paramarray.toString().replace(/\<\<br\>?([^\n]*)\s\<br\>/g,"$1");
paramarray = param+",<a></a>".split(",");
paramarray2 = param.split("\n");
six = six.replace(twotable, "<div class=\"table\"><table class=\"wiki-table\"><tbody><identifier>");


for(loop = 1; loop< paramlen;loop++){
	
	
	six = six.replace("<identifier>","<td><p>"+realparam[loop]+"</p></td><identifier>");

	}

six = six.replace("<identifier>","</tbody><table></div><hr>\ntable generated by plugin table");


return six;
}

